export type Course = {
  id: string;
  title: string;
  originalPrice: string;
  discountedPrice: string;
  discountPercentage: string;
};

export type CourseDetails = {
  id: string;
  is_sebi_flow_enabled: string;
  access_requested: number;
  allow_payment: string;
  bharat_emi_price: number;
  book: string | null;
  book_compulsory: string;
  book_id: string;
  categories: string;
  course_demo_pdf: string;
  course_demo_video: string;
  course_description: string;
  course_feature_1: string;
  course_feature_2: string;
  course_feature_3: string;
  course_feature_4: string;
  course_feature_5: string;
  course_name: string;
  course_slug: string;
  course_thumbnail: string;
  currency: string;
  disable_discount_code: string;
  disable_invoice: string;
  enable: string;
  enable_broker_purchase: string;
  enable_download: string;
  enable_international_pricing: string;
  enable_rich_snippets: string;
  enable_tabs_control: string;
  end_date: string;
  exam_category: string;
  exam_logo: string;
  exam_name: string;
  expiryDate: string;
  expiry_mode: string;
  extended_validity: string;
  extended_validity_price: string;
  featured_discounts: any[]; // expand if known
  files_count: number;
  folder_wise_course: number;
  gif_display: string;
  images_count: number;
  installment_price: number;
  installmentplan: any[]; // expand if known
  is_aadhar_mandatory: string;
  is_combo: number;
  is_doubts_attached: string;
  is_featured: string;
  is_groupchat_enabled: string;
  is_paid: number;
  is_tgconnect_enabled: number;
  jsonld_schema: string;
  language: string;
  likes_count: string;
  live_class_count: number;
  meta_description: string;
  meta_title: string;
  mrp: string;
  noofinstallment: string;
  parent_id: string;
  pdf_count: number;
  perinstallment_validity: string;
  perinstallment_validity_type: string;
  price: string;
  price_kicker: string;
  price_without_gst: string;
  pricing_plans: any[];
  quiz_count: number;
  seats: number;

  sebi_details: {
    consent_type: string;
    pan_verification_mode: string;
    aadhar_consent_price: string;
    aadhar_inclusive: string;
    pan_inclusive: string;
    pan_verification_price: string;
  };

  show_all_doubts_tab: string;
  show_content_tab: string;
  show_demo_tab: string;
  show_feed_tab: string;
  show_live_upcoming_tab: string;
  show_my_doubts_tab: string;
  show_quiz_tab: string;
  show_telegram_tab: string;
  show_test_tab: string;
  show_web_tab: string;
  showemipay: number;
  small_course_logo: string;
  start_date: string;
  study_material: string | null;
  study_material_compulsory: number;
  study_material_id: number;
  sub_exam_category: string;
  subscription_flag: string;
  subscription_plans: any[];
  teacher_id: number;
  teacher_image: string;
  teacher_name: string;
  test_count: number;
  test_pass_compulsory: string;
  test_series_id: string;
  tests_count: number;
  tg_channel_name: string;
  type: string;
  uhs_price: string;
  upsell_items: any[];
  validity: string;
  validity_type: string;
  video_count: number;
  videos_count: number;
  view_in_web: string;
  vod_courses: string;
};

export type PurchasedCourse = {
  purchaseid: string;
  invoice_url: string;
  is_invoice_signed: string; // "0" | "1"
  download_link: string;
  certificate_url: string;
  coursedt: CourseDetails[]; // full course details
  datetime: string; // "YYYY-MM-DD HH:mm:ss"
  enddatetime: string; // "YYYY-MM-DD"
  folder_wise_course: number;
  is_already_expired: number; // 0 | 1
  itemid: string;
  itemtype: string;
  itemtypeid: number;
  purchaseStrToTime: number;
  transactionid: string;
};

export type UserPurchasesResponse = {
  status: number;
  msg: string;
  message: string;
  data: PurchasedCourse[];
};

export type WebSliderItem = {
  id: string;
  image_link: string;
  connected_link: string;
  app_category: string;
  sortingparam: string;
  deleted: string;
};

export type WebSliderResponse = {
  message: string;
  status: number;
  data: WebSliderItem[];
};

export type CurrencyRates = {
  AED: number;
  AUD: number;
  BDT: number;
  BGN: number;
  BRL: number;
  CAD: number;
  CHF: number;
  CNY: number;
  CZK: number;
  DKK: number;
  EUR: number;
  GBP: number;
  HKD: number;
  HRK: number;
  HUF: number;
  IDR: number;
  ILS: number;
  INR: number;
  ISK: number;
  JPY: number;
  KRW: number;
  MXN: number;
  MYR: number;
  NOK: number;
  NPR: number;
  NZD: number;
  PHP: number;
  PKR: number;
  PLN: number;
  RON: number;
  RUB: number;
  SAR: number;
  SEK: number;
  SGD: number;
  THB: number;
  TRY: number;
  USD: number;
  ZAR: number;
};

export type FolderContentItem = {
  id: string;
  parent_id: string;
  Title: string;
  description: string;
  hls_stream_type: string;
  app_status: string;
  chat_status: string;
  concept: number;
  cookie_key: string;
  cookie_value: string;
  course_id: string;
  current_position: number;
  date_and_time: string;
  download_link: string;
  download_link2: string;
  download_links: string[];
  download_url_higher_version: string;
  download_url_lower_version: string;
  duration: string;
  embed_url: string;
  enable_video_download: string;
  enable_video_restrictions: number;
  encrypted_links: string[];
  event_date: string;
  exam: string;
  file_link: string;
  files_count: string;
  filter: string;
  filter_name: string;
  folder_wise_course: number;
  free_flag: number;
  images_count: string;
  is_pdf2_encrypted: string;
  is_pdf_encrypted: string;
  is_premiere: string;
  is_purchased: string;
  iv_string: string;
  links: string[];
  live_quiz_id: number;
  live_rewind_enable: string;
  live_status: number;
  live_type: string;
  livestream_links: string[];
  low_latency_enabled: boolean;
  material_type: string;
  max_time_allowed: string;
  media_id: string;
  meeting_id: string;
  meeting_password: string;
  open_outside_flag: string;
  pdf2_encryption_key: string;
  pdf2_encryption_version: string;
  pdf_encryption_key: string;
  pdf_encryption_version: string;
  pdf_link: string;
  pdf_link2: string;
  quiz_count: string;
  quiz_title_id: string;
  rec_domain: string;
  recording_hls: string;
  recording_schedule: string | null;
  recording_type: string;
  save_flag: string;
  section: number;
  sortingparam: string;
  special_course: string | null;
  strtotime: number;
  study_material_link: string;
  subject: number;
  test_title_id: string;
  tests_count: string;
  thumbnail: string;
  topic: number;
  uhs_version: string;
  video_id: string;
  video_key: string;
  video_player_lower_url: string;
  video_player_token: string;
  video_player_url: string;
  videos_count: string;
  webdrm_links: string[];
  ytFlag: number;
  ytFlagWeb: number;
};

export type FolderContentsResponse = {
  message: string;
  status: number;
  data: FolderContentItem[];
  total: number;
};

export type FeaturedCoursesResponse = {
  message: string;
  msg: string;
  status: number;
  total: number;
  data: CourseDetails[];
};
