export type ParentFolderContentItem = {
  app_status: string;
  audio_link: string;
  chat_status: string;
  course_id: string;
  created_at: string | null;
  creator_id: string;
  date_and_time: string;
  deleted: string;
  description: string;
  drm_enabled: string;
  drm_mp4_url: string;
  duration: string;
  enable: string;
  enable_video_download: string;
  encrypted_links: string;
  event_date: string;
  files_count: string;
  hls_clear_key_ios: string;
  hls_clear_key_urls: string;
  hls_stream_type: string;
  id: string;
  image: string;
  images_count: string;
  is_pdf2_encrypted: string;
  is_pdf_encrypted: string;
  is_premiere: string;
  last_modified_at: string | null;
  link: string | null;
  live_hls_urls: string | null;
  live_link: string;
  live_rewind_enable: string;
  live_type: string;
  max_per_video_views: string;
  max_video_watch_time: string;
  meeting_id: string;
  meeting_password: string;
  parent_id: string | null;
  pdf2_encryption_key: string;
  pdf2_encryption_version: string;
  pdf_encryption_key: string;
  pdf_encryption_version: string;
  pdf_link: string;
  pdf_link2: string;
  quiz_count: string;
  quiz_title_id: string;
  raw_mp4_links: string;
  recording_type: string;
  recordings: string | null;
  room: string | null;
  rtmp_url: string | null;
  save_pdf: string;
  sortingparam: string;
  status: string;
  stream_status: string | null;
  study_material_link: string;
  suggested_thumbnail: string;
  teacher_id: string;
  test_id: string;
  tests_count: string;
  title: string;
  type: string;
  uhs_version: string;
  uniqueidentity: string;
  updated_at: string;
  videos_count: string;
  views: string;
  vuid: string;
  webdrm_links: string;
};

export type ParentFolderResponse = {
  data: ParentFolderContentItem[];
  message: string;
  status: number;
  total: number;
};

export type FolderContentItem = {
  id: string;
  parent_id: string;
  Title: string;
  description: string;
  hls_stream_type: string;
  app_status: string;
  chat_status: string;
  concept: number;
  cookie_key: string;
  cookie_value: string;
  course_id: string;
  current_position: number;
  date_and_time: string;
  download_link: string;
  download_link2: string;
  download_links: string[];
  download_url_higher_version: string;
  download_url_lower_version: string;
  duration: string;
  embed_url: string;
  enable_video_download: string;
  enable_video_restrictions: number;
  encrypted_links: string[];
  event_date: string;
  exam: string;
  file_link: string;
  files_count: string;
  filter: string;
  filter_name: string;
  folder_wise_course: number;
  free_flag: number;
  images_count: string;
  is_pdf2_encrypted: string;
  is_pdf_encrypted: string;
  is_premiere: string;
  is_purchased: string;
  iv_string: string;
  links: string[];
  live_quiz_id: number;
  live_rewind_enable: string;
  live_status: number;
  live_type: string;
  livestream_links: string[];
  low_latency_enabled: boolean;
  material_type: string;
  max_time_allowed: string;
  media_id: string;
  meeting_id: string;
  meeting_password: string;
  open_outside_flag: string;
  pdf2_encryption_key: string;
  pdf2_encryption_version: string;
  pdf_encryption_key: string;
  pdf_encryption_version: string;
  pdf_link: string;
  pdf_link2: string;
  quiz_count: string;
  quiz_title_id: string;
  rec_domain: string;
  recording_hls: string;
  recording_schedule: string | null;
  recording_type: string;
  save_flag: string;
  section: number;
  sortingparam: string;
  special_course: string | null;
  strtotime: number;
  study_material_link: string;
  subject: number;
  test_title_id: string;
  tests_count: string;
  thumbnail: string;
  topic: number;
  uhs_version: string;
  video_id: string;
  video_key: string;
  video_player_lower_url: string;
  video_player_token: string;
  video_player_url: string;
  videos_count: string;
  webdrm_links: string[];
  ytFlag: number;
  ytFlagWeb: number;
};

export type FolderContentResponse = {
  message: string;
  status: number;
  data: FolderContentItem[];
  total: number;
};

export type RootFolderContentItem = {
  Title: string;
  app_status: string;
  chat_status: string;
  concept: number;
  cookie_key: string;
  cookie_value: string;
  course_id: string;
  current_position: number;
  date_and_time: string;
  description: string;
  download_link: string;
  download_link2: string;
  download_links: string[];
  download_url_higher_version: string;
  download_url_lower_version: string;
  duration: string;
  embed_url: string;
  enable_video_download: string;
  enable_video_restrictions: number;
  encrypted_links: string[];
  event_date: string;
  exam: string;
  file_link: string;
  files_count: string;
  filter: string;
  filter_name: string;
  folder_wise_course: number;
  free_flag: number;
  hls_stream_type: string;
  id: string;
  images_count: string;
  is_pdf2_encrypted: string;
  is_pdf_encrypted: string;
  is_premiere: string;
  is_purchased: string;
  iv_string: string;
  links: string[];
  live_quiz_id: number;
  live_rewind_enable: string;
  live_status: number;
  live_type: string;
  livestream_links: string[];
  low_latency_enabled: boolean;
  material_type: string;
  max_time_allowed: string;
  media_id: string;
  meeting_id: string;
  meeting_password: string;
  open_outside_flag: string;
  parent_id: string;
  pdf2_encryption_key: string;
  pdf2_encryption_version: string;
  pdf_encryption_key: string;
  pdf_encryption_version: string;
  pdf_link: string;
  pdf_link2: string;
  quiz_count: string;
  quiz_title_id: string;
  recording_hls: string;
  recording_schedule: string | null;
  recording_type: string;
  save_flag: string;
  section: number;
  sortingparam: string | null;
  special_course: string | null;
  strtotime: number;
  study_material_link: string;
  subject: number;
  test_title_id: string;
  tests_count: string;
  thumbnail: string;
  topic: number;
  uhs_version: string;
  video_id: string;
  video_key: string;
  video_player_lower_url: string;
  video_player_token: string;
  video_player_url: string;
  videos_count: string;
  webdrm_links: string[];
  ytFlag: number;
  ytFlagWeb: number;
};

export type RootFolderContentResponse = {
  message: string;
  status: number;
  data: RootFolderContentItem[];
  total: number;
};
