export type QuizUniqueResponse = {
  status: number;
  msg: string;
  message: string;
  data: {
    exam: string;
  }[];
};

export type QuizTitle = {
  id: string;
  title: string;
  image: string;
  exam: string;
  time: string;
  marks: string;
  pdf_link: string;
  quiz_solutions_video: string;
  show_explanation: string;
  show_instant_solution: string;
  show_rank: string;
  show_results: string;
  show_solutions: string;
  show_solutions_video: string;
  shuffle_questions: string;
  datetimestart: string;
  datetimeend: string;
  datetime: string;
  checkattempt: string;
  totalquestion: number;
};

export type QuizTitleResponse = {
  status: number;
  msg: string;
  message: string;
  total: number;
  data: QuizTitle[];
};

export type QuizAttemptQuestion = {
  id: string;
  quiz_id: string;
  question: string;
  question_image: string;
  option_1: string;
  option_2: string;
  option_3: string;
  option_4: string;
  option_5: string;
  option_image_1: string;
  option_image_2: string;
  option_image_3: string;
  option_image_4: string;
  option_image_5: string;
  answer: string;
  correct_score: string;
  negative_score: string;
  deleted: string;
  difficulty_level: string;
  solution_heading: string;
  solution_text: string;
  solution_image: string;
  solution_video: string;
  sortingparam: string;
};

export type SavedQuestion = {
  id: string;
  question: string;
  headers: string;
  answer: string;
  concept: string;
  difficulty_level: string;
  directive: string;
  exam: string;
  image_link_1: string;
  image_link_2: string;
  image_link_3: string;
  negative_marks: string;
  positive_marks: string;
  option_1: string;
  option_2: string;
  option_3: string;
  option_4: string;
  option_5: string;
  option_6: string;
  option_7: string;
  option_8: string;
  option_9: string;
  option_10: string;
  option_image_1: string;
  option_image_2: string;
  option_image_3: string;
  option_image_4: string;
  option_image_5: string;
  option_image_6: string;
  option_image_7: string;
  option_image_8: string;
  option_image_9: string;
  option_image_10: string;
  question_type: string;
  report_count: string;
  section_id: string;
  solution_heading: string;
  solution_image_1: string;
  solution_image_2: string;
  solution_text: string;
  solution_video: string;
  subject: string;
  test_id: string;
  test_series_id: string;
  test_series_title: string;
  test_title: string;
  topic: string;
};
