export type FeaturedDiscount = {
  id: string;
  coupon_code: string;
  apply_on_ext: string;
  percent_off: string;
  flat_price: string;
  user_id: string;
  item_id: string;
  item_type: string;
  start_date: string;
  expiry_date: string;
  enable: string;
  enable_countdown_timer: string;
  countdown_time: string;
  count: string;
  maxcount: string;
  minimum_order_value: string;
  once_per_user: string;
  maxdiscount: string;
  is_cart_coupon: string;
  is_emi_coupon: string;
  pricing_plan_id: string;
  purchase_item_id: string;
  purchase_item_type: string;
  route_account: string;
  route_account_percentage: string;
  currency: string;
  coupon_type: string;
  deleted: string;
  user_type: string;
};

export type TestSeries = {
  id: string;
  title: string;
  testseries_slug: string;
  exam: string;
  examname: string;
  logo: string;
  banner: string;
  demo_pdf_url: string;
  demo_video_url: string;
  description: string;
  offer_price: number;
  price: number;
  price_kicker: string;
  price_without_gst: string;
  validity: string;
  validity_type: string;
  feature_1: string;
  feature_2: string;
  feature_3: string;
  totaltesttitle: string;
  totaltestpdf: string;
  freetest: string;
  freetestpdf: string;
  paidtest: string;
  paidtestpdf: string;
  offline_test: string;
  bharat_emi_price: string;
  allow_payment: string;
  disable_discount_code: string;
  expiry_mode: string;
  end_date: string;
  gif_display: string;
  test_pass_compulsory: string;
  is_paid: number;
  featured_discounts: FeaturedDiscount[];
};

export type TestSeriesResponse = {
  status: number;
  message: string;
  msg: string;
  total: number;
  data: TestSeries[];
};

export type Subject = {
  subjectid: string;
  subject_name: string;
  subject_logo?: string;
  is_paid?: number;
  sortingparam?: string;
};

export type SubjectsResponse = {
  status: number;
  message: string;
  data: Subject[];
};

export type TestTitle = {
  id: string;
  test_series_id: string;
  title: string;
  language: string;
  marks: string;
  questions: string;
  time: string;
  ui_type: string;
  exam_theme: string;
  free_flag: string;
  attempt_enabled: string;
  attempt_mandatory: string;
  max_test_attempt: string;
  remaining_attempt: string;
  is_test_attempted: boolean;
  is_completed: boolean;
  cutoff_score: string;
  date_time: string;
  enddatetime: string;
  result_date_time: string;
  enable_calculator: string;
  enable_questionpaper: string;
  password: string;
  pdf_url: string;
  maximumsection: string;
  minimumsection: string;
  partial_marking: string;
  partial_scoring_scheme: string;
  show_pause: string;
  show_percentile: string;
  show_rank: string;
  show_result: string;
  show_sectionselector: string;
  show_solutions: string;
  show_solutions_image: string;
  show_solutions_pdf: string;
  show_solutions_video: string;
  shuffle_questions: string;
  shuffle_options: string;
  telegram_link: string;
  telegram_rank: string;
  telegram_score: string;
  test_questions_url: string;
  test_questions_url_2: string;
  test_solutions_link: string;
  test_solutions_image: string;
  test_solutions_pdf: string;
  test_solutions_pdf2: string;
  test_solutions_video: string;
  save_flag: string;
};

export type TestPdf = {
  id: string;
  test_series_id: string;
  title: string;
  type: string;
  date_time: string;
  enddatetime: string;
  exam_theme: string;
  free_flag: number;
  is_completed: boolean;
  is_test_attempted: boolean;
  marks: string;
  max_test_attempt: string;
  negative_marks: string;
  positive_marks: string;
  option_count: string;
  questions: string;
  remainingtime: number;
  all_question_compulsary: string;
  enable_negative_marks_for_fifth_option: string;
  pdf_url: string;
  save_flag: string;
  show_rank: string;
  show_result: string;
  show_solutions: string;
  show_total_students: string;
  solution_pdf: string;
  solution_pdf2: string;
  solution_url: string;
  terms_url: string;
  time: string;
};

export type TestTitleV2Response = {
  message: string;
  status: number;
  test_pdf: TestPdf[];
  test_subjective: [];
  test_titles: TestTitle[];
};

export type Doubt = {
  audio: string;
  course_id: string;
  datetime: string;
  deleted: string;
  doubt: string;
  exam_id: string;
  folder_courses: string;
  id: string;
  image: string;
  is_read: string;
  is_replied: string;
  pdf: string;
  status: string;
  teacher_id: string;
  teacher_name: string;
  timestamp: string;
  user_id: string;
  user_name: string;
};
